create table if not exists global_customer_segment(
customer_segment Integer not null,
customer_segment_description Integer null,
customer_sub_Segment_code varchar(255) null,
customer_sub_segment_description varchar(255) null,
customer_org_segment_code varchar(255) null,
customer_org_segment_description varchar(255) null,
counter_party char null,
ifrs_counter_party varchar(255) null,
hemisphere_code varchar(255) null,
hemisphere_defenition varchar(255) null,
fm_id varchar(255) null,
fm_code varchar(255) null,
fm_short_name varchar(255) null,
valid_entity varchar(255) null,
dat_cust_indicator varchar(255) null,
reference_code varchar(255) null,
effective_record char null,
arm_code varchar(255) null,
entity_state varchar(255) null,
remarks varchar(255) null,
constraint global_customer_segment_pk primary key(customer_segment));